service: tool_name

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  your-function-name:
    handler: tool_name.tool_name.lambda_handler
    events:
      - http:
          path: /
          method: ANY
        cors: true

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePipenv: true
