service: tool-name

provider:
  name: aws
  runtime: python3.9
  stage: ${opt:stage, 'dev'}
  region: eu-west-1

functions:
  tool_name_function:
    handler: tool_name.tool_name.lambda_handler
    events:
      - http:
          path: /
          method: ANY

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: non-linux
    usePipenv: true
