service: basic-serverless-lambda-python

provider:
  name: aws
  runtime: python3.9
  stage: ${env:STAGE, 'dev'}
  region: eu-west-1
  environment:
    PYTHONPATH: /var/task/tool_name
    ENVIRONMENT: ${self:provider.stage}

plugins:
  - serverless-python-requirements

package:
  individually: true

functions:
  theLambda:
    name: test-lambda-${self:provider.stage}
    handler: tool_name.tool_name.lambda_handler
    description: test-lambda-${self:provider.stage}
    timeout: 5 # seconds
    memorySize: 128 # mb
    package:
      patterns:
        - "!node_modules/**"
        - "!yarn.lock"
        - "!package-lock.json"
        - "!package.json"